version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: jmogo
      POSTGRES_USER: jmogo
    ports:
      - "5432:5432"
